In [1]:
import pandas as pd

data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "age": [25, 30, 22, 35, 28, 40, 24, 32],
    "city": ["Delhi", "Mumbai", "Delhi", "Bangalore", "Mumbai", "Delhi", "Bangalore", "Mumbai"],
    "salary": [50000, 65000, 45000, 80000, 55000, 90000, 48000, 70000],
    "department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Finance", "IT"]
}

df = pd.DataFrame(data)
print(df)

      name  age       city  salary department
0    Alice   25      Delhi   50000         IT
1      Bob   30     Mumbai   65000         HR
2  Charlie   22      Delhi   45000         IT
3    David   35  Bangalore   80000    Finance
4      Eva   28     Mumbai   55000         HR
5    Frank   40      Delhi   90000         IT
6    Grace   24  Bangalore   48000    Finance
7    Henry   32     Mumbai   70000         IT

In [2]:
df

      name  age       city  salary department
0    Alice   25      Delhi   50000         IT
1      Bob   30     Mumbai   65000         HR
2  Charlie   22      Delhi   45000         IT
3    David   35  Bangalore   80000    Finance
4      Eva   28     Mumbai   55000         HR
5    Frank   40      Delhi   90000         IT
6    Grace   24  Bangalore   48000    Finance
7    Henry   32     Mumbai   70000         IT

In [3]:
df.shape()

TypeError: 'tuple' object is not callable

In [4]:
df.shape

(8, 5)

In [5]:
df.column

AttributeError: 'DataFrame' object has no attribute 'column'

In [6]:
df.column()

AttributeError: 'DataFrame' object has no attribute 'column'

In [7]:
df.columns

Index(['name', 'age', 'city', 'salary', 'department'], dtype='str')

In [8]:
df.rows

AttributeError: 'DataFrame' object has no attribute 'rows'

In [9]:
df.row

AttributeError: 'DataFrame' object has no attribute 'row'

In [10]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [11]:
df.front

AttributeError: 'DataFrame' object has no attribute 'front'

In [12]:
df.start

AttributeError: 'DataFrame' object has no attribute 'start'

In [13]:
df.front()

AttributeError: 'DataFrame' object has no attribute 'front'

In [14]:
df.head

<bound method NDFrame.head of       name  age       city  salary department
0    Alice   25      Delhi   50000         IT
1      Bob   30     Mumbai   65000         HR
2  Charlie   22      Delhi   45000         IT
3    David   35  Bangalore   80000    Finance
4      Eva   28     Mumbai   55000         HR
5    Frank   40      Delhi   90000         IT
6    Grace   24  Bangalore   48000    Finance
7    Henry   32     Mumbai   70000         IT>

In [15]:
df.tail(3)

    name  age       city  salary department
5  Frank   40      Delhi   90000         IT
6  Grace   24  Bangalore   48000    Finance
7  Henry   32     Mumbai   70000         IT

In [16]:
df

      name  age       city  salary department
0    Alice   25      Delhi   50000         IT
1      Bob   30     Mumbai   65000         HR
2  Charlie   22      Delhi   45000         IT
3    David   35  Bangalore   80000    Finance
4      Eva   28     Mumbai   55000         HR
5    Frank   40      Delhi   90000         IT
6    Grace   24  Bangalore   48000    Finance
7    Henry   32     Mumbai   70000         IT

In [17]:
df["name"]

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
5      Frank
6      Grace
7      Henry
Name: name, dtype: str

In [18]:
df[["name", "age"]]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   22
3    David   35
4      Eva   28
5    Frank   40
6    Grace   24
7    Henry   32

In [19]:
df.query("salary > 60000")

    name  age       city  salary department
1    Bob   30     Mumbai   65000         HR
3  David   35  Bangalore   80000    Finance
5  Frank   40      Delhi   90000         IT
7  Henry   32     Mumbai   70000         IT

In [24]:
df[df["age"] >= 30]

    name  age       city  salary department
1    Bob   30     Mumbai   65000         HR
3  David   35  Bangalore   80000    Finance
5  Frank   40      Delhi   90000         IT
7  Henry   32     Mumbai   70000         IT

In [27]:
df.query("age >= 30")

    name  age       city  salary department
1    Bob   30     Mumbai   65000         HR
3  David   35  Bangalore   80000    Finance
5  Frank   40      Delhi   90000         IT
7  Henry   32     Mumbai   70000         IT

In [28]:
df.query(" city =='Delhi'")

      name  age   city  salary department
0    Alice   25  Delhi   50000         IT
2  Charlie   22  Delhi   45000         IT
5    Frank   40  Delhi   90000         IT

In [29]:
df

      name  age       city  salary department
0    Alice   25      Delhi   50000         IT
1      Bob   30     Mumbai   65000         HR
2  Charlie   22      Delhi   45000         IT
3    David   35  Bangalore   80000    Finance
4      Eva   28     Mumbai   55000         HR
5    Frank   40      Delhi   90000         IT
6    Grace   24  Bangalore   48000    Finance
7    Henry   32     Mumbai   70000         IT

In [34]:
df.query("city == 'Delhi' and salary >= 50000")

    name  age   city  salary department
0  Alice   25  Delhi   50000         IT
5  Frank   40  Delhi   90000         IT

In [48]:
df.query("department == 'IT'")[["name", "age", "salary"]]

      name  age  salary
0    Alice   25   50000
2  Charlie   22   45000
5    Frank   40   90000
7    Henry   32   70000

In [51]:
df["bonus"]= df["salary"].apply(lambda x : x / 10)

In [52]:
df

      name  age       city  salary department   bonus
0    Alice   25      Delhi   50000         IT  5000.0
1      Bob   30     Mumbai   65000         HR  6500.0
2  Charlie   22      Delhi   45000         IT  4500.0
3    David   35  Bangalore   80000    Finance  8000.0
4      Eva   28     Mumbai   55000         HR  5500.0
5    Frank   40      Delhi   90000         IT  9000.0
6    Grace   24  Bangalore   48000    Finance  4800.0
7    Henry   32     Mumbai   70000         IT  7000.0

In [53]:
df["annual_salary"]= df["salary"].apply(lambda x: x*12)

In [54]:
df

      name  age       city  salary department   bonus  annual_salary
0    Alice   25      Delhi   50000         IT  5000.0         600000
1      Bob   30     Mumbai   65000         HR  6500.0         780000
2  Charlie   22      Delhi   45000         IT  4500.0         540000
3    David   35  Bangalore   80000    Finance  8000.0         960000
4      Eva   28     Mumbai   55000         HR  5500.0         660000
5    Frank   40      Delhi   90000         IT  9000.0        1080000
6    Grace   24  Bangalore   48000    Finance  4800.0         576000
7    Henry   32     Mumbai   70000         IT  7000.0         840000

In [62]:
df["name"].count()

np.int64(8)

In [65]:
df.sort_values("salary", ascending=False)

      name  age       city  salary department   bonus  annual_salary
5    Frank   40      Delhi   90000         IT  9000.0        1080000
3    David   35  Bangalore   80000    Finance  8000.0         960000
7    Henry   32     Mumbai   70000         IT  7000.0         840000
1      Bob   30     Mumbai   65000         HR  6500.0         780000
4      Eva   28     Mumbai   55000         HR  5500.0         660000
0    Alice   25      Delhi   50000         IT  5000.0         600000
6    Grace   24  Bangalore   48000    Finance  4800.0         576000
2  Charlie   22      Delhi   45000         IT  4500.0         540000

In [66]:
df.sort_index()

      name  age       city  salary department   bonus  annual_salary
0    Alice   25      Delhi   50000         IT  5000.0         600000
1      Bob   30     Mumbai   65000         HR  6500.0         780000
2  Charlie   22      Delhi   45000         IT  4500.0         540000
3    David   35  Bangalore   80000    Finance  8000.0         960000
4      Eva   28     Mumbai   55000         HR  5500.0         660000
5    Frank   40      Delhi   90000         IT  9000.0        1080000
6    Grace   24  Bangalore   48000    Finance  4800.0         576000
7    Henry   32     Mumbai   70000         IT  7000.0         840000

In [69]:
df=df.sort_values("salary", ascending=False)

In [70]:
df

      name  age       city  salary department   bonus  annual_salary
5    Frank   40      Delhi   90000         IT  9000.0        1080000
3    David   35  Bangalore   80000    Finance  8000.0         960000
7    Henry   32     Mumbai   70000         IT  7000.0         840000
1      Bob   30     Mumbai   65000         HR  6500.0         780000
4      Eva   28     Mumbai   55000         HR  5500.0         660000
0    Alice   25      Delhi   50000         IT  5000.0         600000
6    Grace   24  Bangalore   48000    Finance  4800.0         576000
2  Charlie   22      Delhi   45000         IT  4500.0         540000

In [71]:
df.reset_index(drop=True, inplace=True)

In [72]:
df

      name  age       city  salary department   bonus  annual_salary
0    Frank   40      Delhi   90000         IT  9000.0        1080000
1    David   35  Bangalore   80000    Finance  8000.0         960000
2    Henry   32     Mumbai   70000         IT  7000.0         840000
3      Bob   30     Mumbai   65000         HR  6500.0         780000
4      Eva   28     Mumbai   55000         HR  5500.0         660000
5    Alice   25      Delhi   50000         IT  5000.0         600000
6    Grace   24  Bangalore   48000    Finance  4800.0         576000
7  Charlie   22      Delhi   45000         IT  4500.0         540000

In [73]:
df.sort_values("age", ascending=True)

      name  age       city  salary department   bonus  annual_salary
7  Charlie   22      Delhi   45000         IT  4500.0         540000
6    Grace   24  Bangalore   48000    Finance  4800.0         576000
5    Alice   25      Delhi   50000         IT  5000.0         600000
4      Eva   28     Mumbai   55000         HR  5500.0         660000
3      Bob   30     Mumbai   65000         HR  6500.0         780000
2    Henry   32     Mumbai   70000         IT  7000.0         840000
1    David   35  Bangalore   80000    Finance  8000.0         960000
0    Frank   40      Delhi   90000         IT  9000.0        1080000

In [74]:
df

      name  age       city  salary department   bonus  annual_salary
0    Frank   40      Delhi   90000         IT  9000.0        1080000
1    David   35  Bangalore   80000    Finance  8000.0         960000
2    Henry   32     Mumbai   70000         IT  7000.0         840000
3      Bob   30     Mumbai   65000         HR  6500.0         780000
4      Eva   28     Mumbai   55000         HR  5500.0         660000
5    Alice   25      Delhi   50000         IT  5000.0         600000
6    Grace   24  Bangalore   48000    Finance  4800.0         576000
7  Charlie   22      Delhi   45000         IT  4500.0         540000